<?php include 'header.php';?>
<?php include 'menu_bar.php';?>

	<section>
		<div class="container max-w-lg-down-none m-b-20 bg-white p-5">
			<h2 class="h2 m-b-30 primaryTextColor">Privacy Policy</h2>
			<div class="row">
				<div class="col">
					<h3 class="h3 font-w600">Personal Information:</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD. is the licensed owner of the brand onlymeat and the website ONLYMEAT.in ("The Site"). LIVRAISON FOOD PRODUCTS PVT LTD. respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by LIVRAISON FOOD PRODUCTS PVT LTD. on the Site. As a visitor to the Site/ Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by LIVRAISON FOOD PRODUCTS PVT LTD. in the manner provided in this Privacy Policy.</p>
				<h3 class="h3 font-w600">What information is, or may be, collected form you?</h3>
				<p>As part of the registration process on the Site, LIVRAISON FOOD PRODUCTS PVT LTD. may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information.</p>
				<h3 class="h3 font-w600">How do we collect the Information?</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD. will collect personally identifiable information about you only as part of a voluntary registration process, on-line survey or any combination thereof. The Site may contain links to other Web sites. LIVRAISON FOOD PRODUCTS PVT LTD. is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the Double-click cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site.</p>
				<h3 class="h3 font-w600">How is information used?</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD.will use your personal information to provide personalized features to you on the Site and to provide for promotional offers to you through the Site and other channels. LIVRAISON FOOD PRODUCTS PVT LTD. will also provide this information to its business associates and partners to get in touch with you when necessary to provide the services requested by you. LIVRAISON FOOD PRODUCTS PVT LTD. will use this information to preserve transaction history as governed by existing law or policy. LIVRAISON FOOD PRODUCTS PVT LTD.may also use contact information internally to direct its efforts for product improvement, to contact you as a survey respondent, to notify you if you win any contest; and to send you promotional materials from its contest sponsors or advertisers. LIVRAISON FOOD PRODUCTS PVT LTD. will also use this information to serve various promotional and advertising materials to you via display advertisements through the Google Ad network on third party websites. You can opt out of Google Analytics for Display Advertising and customize Google Display network ads using the Ads Preferences Manager. Information about Customers on an aggregate (excluding any information that may identify you specifically) covering Customer transaction data and Customer demographic and location data may be provided to partners of LIVRAISON FOOD PRODUCTS PVT LTD. for the purpose of creating additional features on the website, creating appropriate merchandising or creating new products and services and conducting marketing research and statistical analysis of customer behavior and transactions.
				With whom your information will be shared
				LIVRAISON FOOD PRODUCTS PVT LTD. will not use your financial information for any purpose other than to complete a transaction with you. LIVRAISON FOOD PRODUCTS PVT LTD. does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services you've requested and such information is necessary to provide these products or services the information may be shared with LIVRAISON FOOD PRODUCTS PVT LTD.'s business associates and partners. LIVRAISON FOOD PRODUCTS PVT LTD. may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition LIVRAISON FOOD PRODUCTS PVT LTD. may use this information for promotional offers, to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, potential threat to the safety or security of any person, violations of the Site's terms of use or to defend against legal claims; special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure.
				What Choice are available to you regarding collection, use and distribution of your information?
				To protect against the loss, misuse and alteration of the information under its control, LIVRAISON FOOD PRODUCTS PVT LTD. has in place appropriate physical, electronic and managerial procedures. For example, LIVRAISON FOOD PRODUCTS PVT LTD. servers are accessible only to authorized personnel and your information is shared with employees and authorized personnel on a need to know basis to complete the transaction and to provide the services requested by you. Although LIVRAISON FOOD PRODUCTS PVT LTD. will endeavor to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this site, you agree that LIVRAISON FOOD PRODUCTS PVT LTD. will have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties.</p>
				<h3 class="h3 font-w600">How can you correct inaccuracies in the information?</h3>
				<p>To correct or update any information you have provided, the Site allows you to do it online. In the event of loss of access details you can send an e-mail to: <a href="cdn-cgi/l/email-protection.php" class="__cf_email__" data-cfemail="51383f373e113e3f3d283c3430257f383f">[email&#160;protected]</a></p>
				<h3 class="h3 font-w600">Policy updates</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD. reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the Site.
				</p>
				</div>
			</div>
		</div>
	</section>


<?php include 'footer.php';?>
