<?php include 'header.php';?>
<?php include 'menu_bar.php';?>

	<section>
		<div class="container max-w-lg-down-none m-b-20 bg-white p-5">
			<h2 class="h2 m-b-30 primaryTextColor">Terms & Condtions</h2>
			<div class="row">
				<div class="col-lg-12">
				<h3 class="h3 font-w600">Personal Information:</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD. is the licensed owner of the brand onlymeat and the website ONLYMEAT.in ("The Site"). LIVRAISON FOOD PRODUCTS PVT LTD. respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by LIVRAISON FOOD PRODUCTS PVT LTD. on the Site. As a visitor to the Site/ Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by LIVRAISON FOOD PRODUCTS PVT LTD. in the manner provided in this Privacy Policy.</p>
				<h3 class="h3 font-w600">Services overview:</h3>
				<p>As part of the registration process on the Site, LIVRAISON FOOD PRODUCTS PVT LTD. may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information.</p>
				<h3 class="h3 font-w600">Eligibility</h3>
				<p>Services of the Site would be available to only select geographies in India. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. If you are a minor i.e. under the age of 18 years but at least 13 years of age you may use the Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Use. If your age is below 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption and the sale of which to minors is prohibited.</p>
				<h3 class="h3 font-w600">License & Site access:</h3>
				<p>LIVRAISON FOOD PRODUCTS PVT LTD. grants you a limited sub-license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of LIVRAISON FOOD PRODUCTS PVT LTD.. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of LIVRAISON FOOD PRODUCTS PVT LTD.. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Site or of LIVRAISON FOOD PRODUCTS PVT LTD. and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilizing the Site's or LIVRAISON FOOD PRODUCTS PVT LTD.'s name or trademarks without the express written consent of LIVRAISON FOOD PRODUCTS PVT LTD.. Any unauthorized use terminates the permission or license granted by LIVRAISON FOOD PRODUCTS PVT LTD..</p>
				<h3 class="h3 font-w600">Pricing:</h3>
				<p>All the products listed on the Site will be sold at MRP unless otherwise specified. The prices mentioned at the time of ordering will be the prices charged on the date of the delivery. Although prices of most of the products do not fluctuate on a daily basis but some of the commodities and fresh meat prices do change on a daily basis. In case the prices are higher or lower on the date of delivery not additional charges will be collected or refunded as the case may be at the time of the delivery of the order. Cancellation by Site / Customer You as a customer can cancel your order anytime up to the cut-off time of the slot for which you have placed an order by calling our customer service. In such a case we will refund any payments already made by you for the order. If we suspect any fraudulent transaction by any customer or any transaction which defies the terms & conditions of using the website, we at our sole discretion could cancel such orders. We will maintain a negative list of all fraudulent transactions and customers and would deny access to them or cancel any orders placed by them.</p>
				</div>
			</div>
		</div>
	</section>

<?php include 'footer.php';?>
